version: "3.8"
services:
  database:
    image: postgres:14.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./script:/docker-entrypoint-initdb.d"
    ports:
      - "5433:5432"
