services:
  pg-sf:
    image: postgres:14.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"